# version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user        
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: worldplaydb  
    ports:
      - "5432:5432"

  app-server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - db

  media-server:
    build:
      context: .
      dockerfile: packages/media-server/Dockerfile
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    ports:
      - "8000:8000"
      - "10000-10100:10000-10100/udp"
      - "10000-10100:10000-10100/tcp"
    depends_on:
      - db